### ISSUE TITLE
Some weird error in depolyment...

### ISSUE THREAD

**Issue by shinaoka** [tensor4all/T4APlutoExamples#22]
https://github.com/tensor4all/T4APlutoExamples/actions/runs/11942713728/job/33290318294

**Comment by terasakisatoshi** [comment]
We should update ExportPluto.yml something like:

```yml
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v4
              if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: ./pluto_notebooks # <-- here
                  single-commit: true
```
